services:
  - type: web
    name: srclient-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: v75eur/srclient
      - key: GITHUB_BRANCH
        value: main
      - key: CURRENT_TOPIC
        value: sr-alertes-2026-09
      - key: PYTHON_VERSION
        value: 3.11.0
